// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pptgzavxpdltcuqpcovo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwdGd6YXZ4cGRsdGN1cXBjb3ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5NjI4NTIsImV4cCI6MjA4OTUzODg1Mn0.b6d7BN_e-2MM8k_8XB85wa1b4SXIMjunDL0xy2eBT1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});